import { FEATURES_ENV } from "@/types/Features";

export const FeatureEnv: FEATURES_ENV = {
  NEXT_PUBLIC_FEATURE_IS_PROFILE_TABS_PHASE_2:
    process.env.NEXT_PUBLIC_FEATURE_IS_PROFILE_TABS_PHASE_2!,
  NEXT_PUBLIC_FEATURE_IS_WALLET_CREDIT_PHASE_2:
    process.env.NEXT_PUBLIC_FEATURE_IS_WALLET_CREDIT_PHASE_2!,
  NEXT_PUBLIC_FEATURE_IS_PACKAGE_PROMOTION_PHASE_2:
    process.env.NEXT_PUBLIC_FEATURE_IS_PACKAGE_PROMOTION_PHASE_2!,
  NEXT_PUBLIC_FEATURE_IS_LANGUAGE_DROPDOWN_PHASE_3:
    process.env.NEXT_PUBLIC_FEATURE_IS_LANGUAGE_DROPDOWN_PHASE_3!,
  NEXT_PUBLIC_FEATURE_IS_MONTHLY_GOLD_PLAN_ONLY:
    process.env.NEXT_PUBLIC_FEATURE_IS_MONTHLY_GOLD_PLAN_ONLY!,
  NEXT_PUBLIC_FEATURE_IS_RESTRICTED_REGION:
    process.env.NEXT_PUBLIC_FEATURE_IS_RESTRICTED_REGION!,
};
