export enum JSON_TYPES {
  VERIFICATION = "verification",
  PAYMENT = "payment",
  MAIN_LAYOUT = "mainLayout",
  COMMON = "common",
  SIGNUP = "signup",
  LOGIN = "login",
  FORGOT_PASSWORD = "forgotPassword",
  RESET_PASSWORD = "resetPassword",
  ABOUT = "about",
  PROFILE = "profile",
  TERMS_AND_CONDITION = "termsAndCondition",
  PRIVACY_STATEMENT = "privacyStatement",
  MOBILE_VERIFICATION = "mobileVerification",
  HOME = "home",
  SUBMITTED_FOR_REVIEW = "submittedForReview",
  COOKIE_STATEMENT = "cookieStatement",
  AFFILIATE = "affiliate",
  CONTACT_US = "contactUs",
  AFFILIATE_PROGRAM = "affiliateProgram",
  FAQ = "faq",
  DETAILS = "details",
  MEMBERSHIP = "membership",
  PHOTOSHOOT = "photoshoot",
  CREDITS = "credits",
  BILLING = "billing",
}
